name: rizq
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  get_it: ^9.0.5
  flutter_svg: ^2.2.1
  bounce: ^1.0.2

  flutter_screenutil: ^5.9.3
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  file_picker: ^10.3.6
  pdfx: ^2.9.2
  pinput: ^5.0.2
  dartz: ^0.10.1
  flutter_animate: ^4.5.2
  equatable: ^2.0.7
  skeletonizer: ^2.1.0+1
  lottie: ^3.3.1
#  dotted_border: ^3.1.0

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  persistent_bottom_nav_bar: ^6.2.1
#  firebase_core: ^3.6.0
#  firebase_messaging: ^15.1.3
#  flutter_local_notifications: ^18.0.1
#  google_sign_in: ^7.2.0


  #local storage packages
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0

  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lang/
    - assets/lotties/
    - assets/images/svg/
    - assets/pngs/
    - assets/svgs/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
# cairo or changa will be removed (wait to select)
    - family: Cairo
      fonts:

        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    - family: Changa
      fonts:
        - asset: assets/fonts/changa/Changa-Light.ttf
          weight: 300
        - asset: assets/fonts/changa/Changa-Regular.ttf
          weight: 400
        - asset: assets/fonts/changa/Changa-Medium.ttf
          weight: 500
        - asset: assets/fonts/changa/Changa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/changa/Changa-Bold.ttf
          weight: 700



